/**
 * Core logic: build the correct env vars for Claude Code to work with any provider.
 *
 * The key insight (and the whole reason this package exists):
 *
 *   ANTHROPIC_API_KEY must be set to EMPTY STRING (""), NOT absent.
 *   If it's missing, Claude Code errors out.
 *   If it's empty, Claude Code falls back to ANTHROPIC_AUTH_TOKEN.
 *
 * This module generates the env vars that make Claude Code work
 * with OpenRouter, DeepSeek, OpenAI, and any Anthropic-compatible proxy.
 */

const { getProvider } = require("./providers");

/**
 * Build environment variables for Claude Code proxy routing.
 *
 * @param {string} provider - Provider name ("openrouter", "deepseek", etc.)
 * @param {object} opts
 * @param {string} opts.apiKey       - Provider API key (required)
 * @param {string} [opts.baseUrl]    - Override base URL
 * @param {string} [opts.model]      - Single model for all tiers
 * @param {string} [opts.haiku]      - Model for haiku tier
 * @param {string} [opts.sonnet]     - Model for sonnet tier
 * @param {string} [opts.opus]       - Model for opus tier
 * @returns {object} Environment variables to set
 * @throws {Error} If provider unknown or apiKey missing
 */
function buildEnv(provider, opts = {}) {
  const cfg = getProvider(provider);
  if (!cfg) {
    throw new Error(
      `Unknown provider "${provider}". ` +
      `Available: openrouter, deepseek, openai, gemini, custom`
    );
  }

  const apiKey = opts.apiKey || process.env[cfg.envKey] || "";
  if (!apiKey) {
    throw new Error(
      `No API key for ${cfg.name}. ` +
      `Pass --key or set ${cfg.envKey} env var.\n` +
      `Get a key: ${cfg.docsUrl}`
    );
  }

  const baseUrl = opts.baseUrl || cfg.baseUrl;
  if (!baseUrl) {
    throw new Error(
      `No base URL for ${cfg.name}. Pass --base-url for custom providers.`
    );
  }

  // Model resolution: explicit > single model > provider defaults
  const modelHaiku  = opts.haiku  || opts.model || cfg.models.haiku;
  const modelSonnet = opts.sonnet || opts.model || cfg.models.sonnet;
  const modelOpus   = opts.opus   || opts.model || cfg.models.opus;

  // Build env vars
  const env = {
    ANTHROPIC_BASE_URL: baseUrl,
    ANTHROPIC_DEFAULT_HAIKU_MODEL:  modelHaiku,
    ANTHROPIC_DEFAULT_SONNET_MODEL: modelSonnet,
    ANTHROPIC_DEFAULT_OPUS_MODEL:   modelOpus,
  };

  if (cfg.auth === "auth_token") {
    // Proxy providers (OpenRouter, Z.AI) use Bearer token
    env.ANTHROPIC_AUTH_TOKEN = apiKey;
    env.ANTHROPIC_API_KEY = "";  // MUST be empty string, NOT absent
  } else {
    // Direct API key providers (DeepSeek, OpenAI)
    env.ANTHROPIC_API_KEY = apiKey;
  }

  return env;
}

/**
 * Format env vars as shell export statements.
 *
 * @param {object} env - Env vars from buildEnv()
 * @returns {string} Shell script with export statements
 */
function toShellExports(env) {
  const lines = ["# Generated by claude-flow — https://github.com/Lexus2016/claude-flow"];
  for (const [key, value] of Object.entries(env)) {
    // Quote values, escape internal quotes
    const escaped = value.replace(/'/g, "'\\''");
    lines.push(`export ${key}='${escaped}'`);
  }
  return lines.join("\n");
}

/**
 * Merge provider env vars into the current process.env.
 * Returns a new env object (does not mutate process.env).
 *
 * @param {string} provider - Provider name
 * @param {object} opts - Same as buildEnv
 * @returns {object} Full env (process.env + provider overrides)
 */
function mergeEnv(provider, opts = {}) {
  const providerEnv = buildEnv(provider, opts);
  const merged = { ...process.env, ...providerEnv };

  // Clean up conflicting keys
  if (providerEnv.ANTHROPIC_AUTH_TOKEN) {
    // When using auth_token, ensure API_KEY is empty (not deleted)
    merged.ANTHROPIC_API_KEY = "";
  }

  return merged;
}

module.exports = { buildEnv, toShellExports, mergeEnv };
